# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neil/learning/plstim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neil/learning/plstim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neil/learning/plstim/CMakeFiles /home/neil/learning/plstim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neil/learning/plstim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named plstim

# Build rule for target.
plstim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plstim
.PHONY : plstim

# fast build rule for target.
plstim/fast:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/build
.PHONY : plstim/fast

#=============================================================================
# Target rules for targets named simple-experiment

# Build rule for target.
simple-experiment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple-experiment
.PHONY : simple-experiment

# fast build rule for target.
simple-experiment/fast:
	$(MAKE) -f CMakeFiles/simple-experiment.dir/build.make CMakeFiles/simple-experiment.dir/build
.PHONY : simple-experiment/fast

apps/simple-experiment/simple-experiment.o: apps/simple-experiment/simple-experiment.cc.o
.PHONY : apps/simple-experiment/simple-experiment.o

# target to build an object file
apps/simple-experiment/simple-experiment.cc.o:
	$(MAKE) -f CMakeFiles/simple-experiment.dir/build.make CMakeFiles/simple-experiment.dir/apps/simple-experiment/simple-experiment.cc.o
.PHONY : apps/simple-experiment/simple-experiment.cc.o

apps/simple-experiment/simple-experiment.i: apps/simple-experiment/simple-experiment.cc.i
.PHONY : apps/simple-experiment/simple-experiment.i

# target to preprocess a source file
apps/simple-experiment/simple-experiment.cc.i:
	$(MAKE) -f CMakeFiles/simple-experiment.dir/build.make CMakeFiles/simple-experiment.dir/apps/simple-experiment/simple-experiment.cc.i
.PHONY : apps/simple-experiment/simple-experiment.cc.i

apps/simple-experiment/simple-experiment.s: apps/simple-experiment/simple-experiment.cc.s
.PHONY : apps/simple-experiment/simple-experiment.s

# target to generate assembly for a file
apps/simple-experiment/simple-experiment.cc.s:
	$(MAKE) -f CMakeFiles/simple-experiment.dir/build.make CMakeFiles/simple-experiment.dir/apps/simple-experiment/simple-experiment.cc.s
.PHONY : apps/simple-experiment/simple-experiment.cc.s

lib/moc_glwidget.o: lib/moc_glwidget.cxx.o
.PHONY : lib/moc_glwidget.o

# target to build an object file
lib/moc_glwidget.cxx.o:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/moc_glwidget.cxx.o
.PHONY : lib/moc_glwidget.cxx.o

lib/moc_glwidget.i: lib/moc_glwidget.cxx.i
.PHONY : lib/moc_glwidget.i

# target to preprocess a source file
lib/moc_glwidget.cxx.i:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/moc_glwidget.cxx.i
.PHONY : lib/moc_glwidget.cxx.i

lib/moc_glwidget.s: lib/moc_glwidget.cxx.s
.PHONY : lib/moc_glwidget.s

# target to generate assembly for a file
lib/moc_glwidget.cxx.s:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/moc_glwidget.cxx.s
.PHONY : lib/moc_glwidget.cxx.s

lib/moc_qexperiment.o: lib/moc_qexperiment.cxx.o
.PHONY : lib/moc_qexperiment.o

# target to build an object file
lib/moc_qexperiment.cxx.o:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/moc_qexperiment.cxx.o
.PHONY : lib/moc_qexperiment.cxx.o

lib/moc_qexperiment.i: lib/moc_qexperiment.cxx.i
.PHONY : lib/moc_qexperiment.i

# target to preprocess a source file
lib/moc_qexperiment.cxx.i:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/moc_qexperiment.cxx.i
.PHONY : lib/moc_qexperiment.cxx.i

lib/moc_qexperiment.s: lib/moc_qexperiment.cxx.s
.PHONY : lib/moc_qexperiment.s

# target to generate assembly for a file
lib/moc_qexperiment.cxx.s:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/moc_qexperiment.cxx.s
.PHONY : lib/moc_qexperiment.cxx.s

lib/qexperiment.o: lib/qexperiment.cc.o
.PHONY : lib/qexperiment.o

# target to build an object file
lib/qexperiment.cc.o:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/qexperiment.cc.o
.PHONY : lib/qexperiment.cc.o

lib/qexperiment.i: lib/qexperiment.cc.i
.PHONY : lib/qexperiment.i

# target to preprocess a source file
lib/qexperiment.cc.i:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/qexperiment.cc.i
.PHONY : lib/qexperiment.cc.i

lib/qexperiment.s: lib/qexperiment.cc.s
.PHONY : lib/qexperiment.s

# target to generate assembly for a file
lib/qexperiment.cc.s:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/qexperiment.cc.s
.PHONY : lib/qexperiment.cc.s

lib/setup.o: lib/setup.cc.o
.PHONY : lib/setup.o

# target to build an object file
lib/setup.cc.o:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/setup.cc.o
.PHONY : lib/setup.cc.o

lib/setup.i: lib/setup.cc.i
.PHONY : lib/setup.i

# target to preprocess a source file
lib/setup.cc.i:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/setup.cc.i
.PHONY : lib/setup.cc.i

lib/setup.s: lib/setup.cc.s
.PHONY : lib/setup.s

# target to generate assembly for a file
lib/setup.cc.s:
	$(MAKE) -f CMakeFiles/plstim.dir/build.make CMakeFiles/plstim.dir/lib/setup.cc.s
.PHONY : lib/setup.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... plstim"
	@echo "... rebuild_cache"
	@echo "... simple-experiment"
	@echo "... apps/simple-experiment/simple-experiment.o"
	@echo "... apps/simple-experiment/simple-experiment.i"
	@echo "... apps/simple-experiment/simple-experiment.s"
	@echo "... lib/moc_glwidget.o"
	@echo "... lib/moc_glwidget.i"
	@echo "... lib/moc_glwidget.s"
	@echo "... lib/moc_qexperiment.o"
	@echo "... lib/moc_qexperiment.i"
	@echo "... lib/moc_qexperiment.s"
	@echo "... lib/qexperiment.o"
	@echo "... lib/qexperiment.i"
	@echo "... lib/qexperiment.s"
	@echo "... lib/setup.o"
	@echo "... lib/setup.i"
	@echo "... lib/setup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

