#############################################################################
# Makefile for building: plstim
# Generated by qmake (2.01a) (Qt 4.8.2) on: jeu. oct. 11 23:54:31 2012
# Project:  plstim.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile plstim.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-lib \
		sub-apps-simple-experiment

lib/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	cd lib/ && $(QMAKE) /home/neil/learning/plstim/lib/lib.pro -o $(MAKEFILE)
sub-lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	cd lib/ && $(QMAKE) /home/neil/learning/plstim/lib/lib.pro -o $(MAKEFILE)
sub-lib: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE)
sub-lib-make_default-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) 
sub-lib-make_default: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) 
sub-lib-make_first-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) first
sub-lib-make_first: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) first
sub-lib-all-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) all
sub-lib-all: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) all
sub-lib-clean-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-lib-clean: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-lib-distclean-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lib-distclean: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lib-install_subtargets-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) install
sub-lib-install_subtargets: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) install
sub-lib-uninstall_subtargets-ordered: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-lib-uninstall_subtargets: lib/$(MAKEFILE) FORCE
	cd lib/ && $(MAKE) -f $(MAKEFILE) uninstall
apps/simple-experiment/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) apps/simple-experiment/ || $(MKDIR) apps/simple-experiment/ 
	cd apps/simple-experiment/ && $(QMAKE) /home/neil/learning/plstim/apps/simple-experiment/simple-experiment.pro -o $(MAKEFILE)
sub-apps-simple-experiment-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) apps/simple-experiment/ || $(MKDIR) apps/simple-experiment/ 
	cd apps/simple-experiment/ && $(QMAKE) /home/neil/learning/plstim/apps/simple-experiment/simple-experiment.pro -o $(MAKEFILE)
sub-apps-simple-experiment: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE)
sub-apps-simple-experiment-make_default-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-make_default-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) 
sub-apps-simple-experiment-make_default: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) 
sub-apps-simple-experiment-make_first-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-make_first-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) first
sub-apps-simple-experiment-make_first: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) first
sub-apps-simple-experiment-all-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-all-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) all
sub-apps-simple-experiment-all: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) all
sub-apps-simple-experiment-clean-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-clean-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) clean
sub-apps-simple-experiment-clean: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) clean
sub-apps-simple-experiment-distclean-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-distclean-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) distclean
sub-apps-simple-experiment-distclean: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) distclean
sub-apps-simple-experiment-install_subtargets-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-install_subtargets-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) install
sub-apps-simple-experiment-install_subtargets: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) install
sub-apps-simple-experiment-uninstall_subtargets-ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-uninstall_subtargets-ordered  FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-apps-simple-experiment-uninstall_subtargets: apps/simple-experiment/$(MAKEFILE) FORCE
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: plstim.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile plstim.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile plstim.pro

qmake_all: sub-lib-qmake_all sub-apps-simple-experiment-qmake_all FORCE

make_default: sub-lib-make_default-ordered sub-apps-simple-experiment-make_default-ordered FORCE
make_first: sub-lib-make_first-ordered sub-apps-simple-experiment-make_first-ordered FORCE
all: sub-lib-all-ordered sub-apps-simple-experiment-all-ordered FORCE
clean: sub-lib-clean-ordered sub-apps-simple-experiment-clean-ordered FORCE
distclean: sub-lib-distclean-ordered sub-apps-simple-experiment-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-lib-install_subtargets-ordered sub-apps-simple-experiment-install_subtargets-ordered FORCE
uninstall_subtargets: sub-lib-uninstall_subtargets-ordered sub-apps-simple-experiment-uninstall_subtargets-ordered FORCE

sub-lib-check_ordered: lib/$(MAKEFILE)
	cd lib/ && $(MAKE) -f $(MAKEFILE) check
sub-apps-simple-experiment-check_ordered: apps/simple-experiment/$(MAKEFILE) sub-lib-check_ordered 
	cd apps/simple-experiment/ && $(MAKE) -f $(MAKEFILE) check
check: sub-lib-check_ordered sub-apps-simple-experiment-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

